language: node_js
node_js:
- '4.0'
- '9.0'
after_script: bash <(curl -s https://codecov.io/bash)
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: EgQ97gmMgZgSIx+EsTPTLTiEg95Sl3pTfHcRq30u2Vu9n24i1JfuhA0/U1GkMcq8UXetp9+shxgVDU+XQ34nYLaTfiQKMHNgSExq9Llkr1QMAR2tzVVD46wYTsAAih+4zm6P3KN787pu/uZYl1gnYMdYkKPRAz7nVO50FoSCUJfGONj4PsaowlVB2hDYzpbNeKiUBnbUD+Nn/pzN/NnFLpGIH2r42mW1vqPEVGMG0xUf4CmC8ED0ISj/8L7vzdEvzztdQv0i6wQzLSPPqoqq8Wt8HAwqaW72cwybwvk6caUT7axV9VIsSH94hKib0SaDeZUtxvvEmo9CYYhYU4uhsdbCJQhBsJRbm6OEwI1UpxerSV3E5uBEf0bnXqyaPac7PWjA5IOm6cxc9CuJ+LGoUqsiIUNlNLEyQhkTjBEbDlG44U2nMEmpGDw5axsbsgAcL8o8tI4FlZrDxGtDiHJ+vrnTILUNjrQlRsvGEWGif1YbKwbWEE75tG35IuCs0DbPPGVVSoSGC09sGywE1022vY5r/BdN2RYX8YyJ/+a0NTAXv7aIveIAKf7QqUuOeYgo0cUZfhI1zvYtKr9YNsw2OLnYosfsBhIpHb+YLJDa9P9nq/GKw+86BO8BqMrvGmh4Vyo8ZKvySU/ffUKD6tFaxfbM65ZSF3fTEboAPy6v8kg=
  file:
    - "hast-util-to-html.js"
    - "hast-util-to-html.min.js"
  on:
    tags: true
    node: '9.0'
